### ISSUE TITLE
x86 configuration not available

### ISSUE THREAD

**Issue by sanidhya26** [doughtmw/HoloLensForCV-Unity#1]
x86 configuration is not available for HololensForCV in configuration manager dropdown.  I wanted to add some extra bit of code to "DepthPvMapper" but not sure how to build it after that..Please help

**Comment by doughtmw** [comment]
That's strange. I'm able to set the HoloLensForCV project to `x86` and build successfully. Are the projects loading correctly in Visual Studio? Make sure you have the required [tools for HoloLens development installed](https://docs.microsoft.com/en-us/windows/mixed-reality/install-the-tools) as well.

**Comment by sanidhya26** [comment]
ya I think I screwed something up while setting up the project..I started from scratch and its working now..Thanks..
