### ISSUE TITLE
hololensforcv project built error: Unable to resolve external symbols...

### ISSUE THREAD

**Issue by susu1234567** [doughtmw/HoloLensForCV-Unity#3]
I want to get output files of hololensforcv project, but it built error because:Unable to resolve external symbols... I konw that maybe configurations' wrong, but do not know how to slove it. Hope you can help me.
   I did not have opencv4.1.1 in my PC and not creat NuGet package(that is necessary?), and I don't know if it can cause the error.
![GRSY3P1L5H0LH~Y`L$Q VXY](https://user-images.githubusercontent.com/44127702/83488728-e8e1dd00-a4df-11ea-808a-428d554197e5.png)

**Comment by doughtmw** [comment]
Hi @susu1234567, I'm glad you're interested in the sample. The Nuget packages linked from my repo are required for building the HoloLensForCV library. Be sure to download them and install them to your HoloLensForCV project prior to attempting to build.
