### ISSUE TITLE
Abnormal depth value

### ISSUE THREAD

**Issue by kaiwu119** [doughtmw/HoloLensForCV-Unity#5]
I successfully configured your project, this is a very good example. But I have some questions to ask you. I changed the code to directly read the depth map information and save it in byte[]. When I display it on the texture, it seems to be almost completely black. My code as follow:
`   var DepthFrame = latestShortDepthCameraFrame.SoftwareBitmap;
            DepthFrame = SoftwareBitmap.Convert(DepthFrame, BitmapPixelFormat.Rgba8, BitmapAlphaMode.Premultiplied);
            var w = DepthFrame.PixelWidth;
            var h = DepthFrame.PixelHeight;
               
             Destroy(_pvDepthTexture);
            _pvDepthTexture = new Texture2D(
                w,
                h,
                TextureFormat.RGBA32, false);
            if (bytes==null)
                {
                    bytes = new byte[w * h * 4];
                }
           
            DepthFrame.CopyToBuffer(bytes.AsBuffer());
            DepthFrame.Dispose();
          
         _pvDepthTexture.LoadRawTextureData(bytes);
                       `
I also noticed that in your example, it seems that all the depths are displayed in white. I am a novice and it is really difficult to understand. Please help me to solve this confusion.

**Comment by mingkyme** [comment]
```cs
_pvDepthTexture.LoadRawTextureData(bytes);
_pvDepthTexture.Apply();
_pvDepthMaterial.mainTexture = _pvDepthTexture;
SendImage(rgbBytes, depthBytes);
```

Did you miss this code?

**Comment by kaiwu119** [comment]
I know where I am wrong. Each value of the depth map is 16 bits. When I read it, I only got the high 8 bits.

I want to ask you another question. Although I know that you no longer use hololens1, I now want to do something on the basis of your program. The program often crashes is a very headache for me. Can you roughly provide the reasons for the program crash, so that I can repair it. Thanks in advance!

**Comment by mingkyme** [comment]
In my case, app crashed cause from increasing of using memory.
Could you check amount of using memory on the Windows Device Portal - Performance - Processes?

**Comment by kaiwu119** [comment]
Yes, you are right, I checked the memory, when work set over 1G, the App crashed.

**Comment by kaiwu119** [comment]
I found that when I just use the code as follow,   the using memory is well.
` 
unsafe void UpdateHoloLensMediaFrameSourceGroup()
{
#if ENABLE_WINMD_SUPPORT
            if (!_mediaFrameSourceGroupsStarted ||
                _pvMediaFrameSourceGroup == null ||
                _shortDepthMediaFrameSourceGroup == null)
            {
                return;
            }
#endif
}
`
But when I add a line,as follow , The memory used will skyrocket. 
` 
unsafe void UpdateHoloLensMediaFrameSourceGroup()
{
#if ENABLE_WINMD_SUPPORT
            if (!_mediaFrameSourceGroupsStarted ||
                _pvMediaFrameSourceGroup == null ||
                _shortDepthMediaFrameSourceGroup == null)
            {
                return;
            }
          // Photo video
            SensorFrame latestPvCameraFrame =
                _pvMediaFrameSourceGroup.GetLatestSensorFrame(
                _sensorType);
#endif
}
`
So it may be a memory leak caused by this line of code, but I don’t know how to fix it, can you provide some suggestions?

**Comment by mingkyme** [comment]
Don't forget about destroy bytes.
https://github.com/doughtmw/HoloLensForCV-Unity/blob/c55ed7ccf844847e1bef8a03a35ff76b74346531/HoloLensForCVUnity/Assets/Scripts/SensorStreams.cs#L231

**Comment by kaiwu119** [comment]
I checked the code and I have destroyed the bytes. I think it is not the problem in this place, I think it is the problem with the following codes.
```
SensorFrame latestPvCameraFrame =
                _pvMediaFrameSourceGroup.GetLatestSensorFrame(
                _sensorType);
```
I know that the return type of **_pvMediaFrameSourceGroup.GetLatestSensorFrame(
                _sensorType);** in the HoloLensForCV code should be SensorFrame^, but in the C# script, it returns a SensorFrame . I don't know if it is due to this reason, because I don't know much about the use of C++/CLI code in C#.

**Comment by mingkyme** [comment]
```cs

        unsafe void UpdateHoloLensMediaFrameSourceGroup()
        {
#if ENABLE_WINMD_SUPPORT
            if (!_mediaFrameSourceGroupsStarted ||
                _pvMediaFrameSourceGroup == null ||
                _shortDepthMediaFrameSourceGroup == null)
            {
                return;
            }

            // Get latest sensor frames
            // Photo video
            SensorFrame latestPvCameraFrame =
                _pvMediaFrameSourceGroup.GetLatestSensorFrame(
                _sensorType);

            // ToF Depth
            SensorFrame latestShortDepthCameraFrame =
                _shortDepthMediaFrameSourceGroup.GetLatestSensorFrame(
                    _sensorTypeResearch);

            Destroy(_pvDepthTexture);
            _pvDepthTexture = new Texture2D(
                latestShortDepthCameraFrame.SoftwareBitmap.PixelWidth,
                latestShortDepthCameraFrame.SoftwareBitmap.PixelHeight,
                TextureFormat.BGRA32, false);
            
            myText.text = latestShortDepthCameraFrame.SoftwareBitmap.DpiX + "/" + latestShortDepthCameraFrame.SoftwareBitmap.DpiY;

            var depthBytes = new byte[4 * latestShortDepthCameraFrame.SoftwareBitmap.PixelWidth * latestShortDepthCameraFrame.SoftwareBitmap.PixelHeight];
            var rgbBytes = new byte[4 * latestPvCameraFrame.SoftwareBitmap.PixelWidth * latestPvCameraFrame.SoftwareBitmap.PixelHeight];
            latestShortDepthCameraFrame.SoftwareBitmap.CopyToBuffer(depthBytes.AsBuffer());
            latestPvCameraFrame.SoftwareBitmap.CopyToBuffer(rgbBytes.AsBuffer());

            _pvDepthTexture.LoadRawTextureData(depthBytes);
            _pvDepthTexture.Apply();
            
            _pvDepthMaterial.mainTexture = _pvDepthTexture;
            SendImage(rgbBytes, depthBytes);


#endif
        }
```

This is my code.
It doesn't increase using memory.

**Comment by kaiwu119** [comment]
Thank you very much, the program will not crash after your guidance.
I have another confusing question. Now I want to output the point cloud coordinates calculated in the DepthPvMapper class to the Unity script. What should I do? Because I found that the return type of the function in the DepthPvMapper class seems only to be HoloLensForCV::SensorFrame^, so that the data can be obtained in the unity script, so my current approach is to separate the x, y, and z coordinates of the 3D point cloud add one and multiply it by 1000 to convert it into integer data.
```
int encoderX = xCoords+1;
```
Then encode and store it in the cv::Mat type, and then convert it to the SensorFrame^ type，finally return. In unity script ，I decoder the xCoords,yCoords and zCoords.
```
HoloLensForCV::SensorFrame^ realDepthSensorFrame =
Utils::WrapCvMatWithHoloLensDepthSensorFrame(res, depthFrame->Timestamp);
```
Although this can bring the data back to the Unity script, it is very troublesome and has a certain loss of precision.
Is there any other way to help me solve this problem?
Thank you again for your help！

**Comment by mingkyme** [comment]
I didn't do next step.
Good Luck!

**Comment by kaiwu119** [comment]
Thank you again for your help.
You are really a nice person！
