### ISSUE TITLE
Initializing MediaFrameSourceGroups...

### ISSUE THREAD

**Issue by ephynes** [doughtmw/HoloLensForCV-Unity#7]
Hi, I followed the instructions in your repo. I have built and deployed the app to the HoloLens 2. I can see the blank Canvas with the Text which never goes beyond the message: _"Initializing MediaFrameSourceGroups"_. I have questions in order to clarify your instructions to make sure I did it correctly:

**In step 2:** I presume I need to create the subfolder folder named x86 in Assets->Plugins in the Unity project and copy the 2 dlls and winmd files into it.

**In step 3:** _"build using IL2CPP"_ Does this involve importing the MRTK2 Foundation package to the Unity project, or does this just involve switching platform to Universal Windows Platform (UWP)? 

**In step 4:** Do I manually edit the \<Capabilities> xxx \</Capabilities> xml myself to match what you've shown or does this happen as a result of editing the code above it during build time.

**In step 5:** To build and deploy from Visual Studio, do I target ARM or ARM64? The HoloLens 2 device does not support x86.

**From your personal blog:**

_" be sure to select the Assembly-CSharp.Player "_: Where can I find this setting in Visual Studio?

**Other potential issues:**

1. I downloaded the zip file from the GitHub repo and worked from there. The _"HoloLensForCV"_ folder is empty when I do this.
2. I am using Unity 2019.4.15f, but there doesn't seem to be any issues with this.
3. Should I manually enable any capabilities in the Player->Publishing Settings ?

I would be obliged and indebted to you if you can clarify these questions. Thank you in advance.

**Comment by Avinash0795** [comment]
Respected Sir,
I did have the same Problem till now....and have been working on this for past 2 weeks and could not find a solution.
https://github.com/doughtmw/ArUcoDetectionHoloLens-Unity/issues/22
Please do check this link... I did receive some answer...If this is helpful to you and if you did find some answer please do let me know.
Thanking you,
Yours sincerely,
Avinash Shanmugam

**Comment by ephynes** [comment]
भाई,

 I have succeeded to deploy a working version of the ArUco sample from:

https://github.com/doughtmw/ArUcoDetectionHoloLens-Unity

which is more relevant to what I need for my project. I followed all of the instructions on the repo with no problem and it works really well. I will now close this thread. Thank you. And thank you Mitchell Doughty. I think it is crazy that the photo / video feed is not straight up available to developers in MRTK2 as with other AR HMDs.

**Comment by Avinash0795** [comment]
Respected Sir,

I used the same website and followed each and every Instruction but again I faced the same issue. Could you just give me a small explanation on your last sentence about the PV feed not available in MRTK2?

Did you also select Assemblyc#.player in Visual studio?

Do you think that we need Researchmode to be enabled for this ?

Do we have to also calibrate the camera of Hololens 2?

I am sorry to post you with so many questions as you have seen a successful deployment, It would be really great for me to get some inputs from you.

Thanking you.

**Comment by ephynes** [comment]
I will describe my set-up and exactly what I did.

1. Windows 10 SDK 10.0.19041.0 (https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk/)
2. Visual Studio 2019 (https://visualstudio.microsoft.com/downloads/)
3. Visual Studio: C++ Universal Windows Platform tools (Select this option when downloading Visual Studio)
4. Visual Studio: build tools v142 (https://visualstudio.microsoft.com/downloads/  (bottom of the page, download separately) )
5. Enable Research mode on HoloLens in web browser (System -> Research Mode -> Allow access to sensor streams (see notes) )
6. Go to https://github.com/doughtmw/ArUcoDetectionHoloLens-Unity and download zip. This will leave the HoloLensCamCalib and HoloLensforCV folders empty on you PC so:
7. Go to https://github.com/doughtmw/HoloLensCamCalib/tree/f4762cc37f148626b5a3ecdb585f420780725314 and download zip. Move all files in to the HoloLensCamCalib folder from the previous step.
8. Go to https://github.com/doughtmw/HoloLensForCV/tree/7ab30ad3be41390b5a0b363d45230283db8884cd, download zip and move all files in to the HoloLensForCV folder from step 9.
9. Now open the Unity project. I am using the latest stable Long-Term Support (LTS): 2019.15f from November 2020 
10. Build Settings -> switch platform to Universal Windows Platform (UWP) 
11. Project Settings -> Player -> **XR settings*** (see notes). Set to 16-bit depth.
12. Build Setting -> Build (choose an output build folder)
13. Once built, Unity will open the output folder. Open the new solution .sln project in Visual Studio **2019**.
14. In the Solution Platforms box I think I selected ARM64, but ARM should work also. I also selected _Remote Machine_ for deploying the app over WiFi. If deploying via USB-C, I believe this must be set to _Device_. I left the Solutions Configuration box set to _Degug_ although _Master_ and _Release_ will work even quicker I believe because they don't use a debugger.
15. If deploying to HoloLens over the air (WiFi via IP address) go into Project ->Properties -> Debugging ->Machine Name and enter the HoloLens' IPv4 address. Click apply.
16. Debug -> Start Debugging. (Make sure HoloLens in on and connected to WiFi).
17. This will build and deploy the app to the device. I takes several minutes. Once done, the app will launch on the device.
17. To test the app, google images of ARUco markers. A cube should appear over detectable markers. 

**NOTES**
Connect Hololens and PC to the same WiFi network. Get HoloLens IP address from HoloLens (Settings -> Network & Internet -> Advanced options ->IPv4 Address). Type this IP address in a web browser URL to access the HoloLens portal to enable research mode. The first time you connect to the HoloLens you will be asked to pair the device with a pin number. Your Windows 10 PC will need to be in development mode also. If browsers blocks access due to security warning, click on _Advanced_ and proceed to IP URL. The first time, you will have to add a user name and password also.

*I have found that it is **Important** to use the old deprecated XR setting in Unity player and **NOT** the new XR Plugin Management option in the left hand side bar. This new XR setting does not seem to be working correctly yet and my apps  were in 2D mode only on the device (within a 2D app window)

It seems that the idea of using the HoloLensForCV C++ files is to use them in Visual Studio to build .dll files that you then copy into the plugins folder in your Unity project in order to use them in your Unity project. In the ArUcoDetectionHoloLens-Unity project, this is already done for us. All of the dll files are already in the plugins folders on the Unity project, so we don't have to do anything more here, which is really great. In .NET 4.x, a Windows MetaData file (.winmd) is the interface between your Unity project and these dll files.

I did not have to calibrate the HoloLens camera in any way.

You don't need the MRTK SDK to run this application. As far as I can tell, continuous access to the camera feed is not provided by the MRTK v2 SDK for the HoloLens 2. In order to access the sensor streams, including the colour video camera, the device needs to be in research mode and you need to use the dlls created from the HoloLensForCV project.

To enable Assembly-CSharp.Player, go to Unity and select Edit -> Preferences -> External Tools -> Player Projects. Then click Regenerate project files. When I did this I got the Assembly-CSharp.Player project structure in Visual Studio where I can see all of the code in colour.

I wish you success with this. Please don't hesitate to ask me any further questions if I have missed something or if any of the steps are unclear.

**OTHER SETTINGS**
If all of the above still doesn't help, then try:

Edit -> Project Settings -> Player -> Settings for UWP tab -> Other Settings -> Configuration -> Api Compatibility Level =.NET 4.x (I think this is important to enable Assembly-CSharp.Player but I also haven't got this working yet)

Edit -> Project Settings -> Player -> Settings for UWP tab -> Publishing Settings -> Capabilities = enable WebCam
